apiVersion: v1
kind: Deployment
metadata: 
   name: mongodb
   namespace: roboshop
   labels:
      project: roboshop
      component: mongodb
      tier: db

spec:
  replicas: 1
  selector: 
    matchLabels:
      project: roboshop
      component: mongodb
      tier: db
  templates:
    metadata:
      labels:
        project: roboshop
        component: mongodb
        tier: db
    spec:
      containers:
      - name: mongodb
        image: muppalasowjanya/mongodb:v1